iprt/Makefile.kmk: Added a test-mangling rule.
svn:sync-xref-src-repo-rev: r70894

diff --git a/src/VBox/Runtime/Makefile.kmk b/src/VBox/Runtime/Makefile.kmk
--- a/src/VBox/Runtime/Makefile.kmk
+++ b/src/VBox/Runtime/Makefile.kmk
@@ -1,4 +1,4 @@
-# $Id: Makefile.kmk 36407 2011-03-24 16:14:57Z knut.osmundsen@oracle.com $
+# $Id: Makefile.kmk 36488 2011-04-01 11:41:08Z knut.osmundsen@oracle.com $
 ## @file
 # Sub-Makefile for the IPRT (IPRT).
 #
@@ -2210,6 +2210,26 @@ test-doxygen::
 	@echo $(IPRT_DOXYFILE_OUTPUT)
 	@echo $(DOXYGEN_OUTPUT_PREV)
 	@echo $(IPRT_DOXYFILE_INPUT)
+
+test-mangling:: $(RuntimeR3_1_TARGET)
+ifn1of ($(KBUILD_TARGET),win)
+	rcExit=0; \
+	for fn in ` nm $(RuntimeR3_1_TARGET) \
+			| $(SED) -n \
+				-e 's/^[0-9a-f][0-9a-f]* //' \
+				-e '/^[TUD]/!d' \
+				-e 's/^. //' \
+				-e '/^RT/p' \
+				-e '/^g_/p' `; \
+	do \
+		if $(SED) -ne '/\#define '"$${fn}"' /q 1' $(PATH_ROOT)/include/iprt/mangling.h; then \
+			echo "mangling.h: Missing '"$${fn}"'"; \
+			rcExit=1;\
+		fi \
+	done; \
+	exit $${rcExit}
+endif
+
 
 #
 # Generate the rules (we're the to sub-makefile).
